### PR TITLE
Add more Elasticsearch versions

### PR DESCRIPTION
**Pull request by johman10**
This will add all the versions that Elasticsearch has put out.

I must be honest here and say that I haven't tested them all, but at least 6.0.1 works. :)

List is based on: https://www.elastic.co/downloads/past-releases

### CODE REVIEW

**Comment by Stratus3D** [comment]
I would love to see this get merged.

**Comment by Stratus3D** [comment]
The build for master is failing already.

**Comment by Stratus3D** [comment]
Ping. It would be nice if we could have something like https://github.com/zoras/asdf-elasticsearch/blob/master/bin/list-all.

This plugin hasn't been updated in over a year, while other plugins https://github.com/zoras/asdf-elasticsearch have been kept updated. I'm considering removing this plugin from the official asdf plugin list.

**Comment by johman10** [comment]
@Stratus3D still no reply from the original maintainer. I see that you didn't change the original docs yet to refer to another client. Are you still planning on it? I might just close this and give up on it. Obviously the repo isn't maintained anymore.

**Comment by johman10** [comment]
Apparently @mikestephens has done [his own update](https://github.com/mikestephens/asdf-elasticsearch/commit/d051793cfddf4f24635b893f9630b57b78f8fdda) to the `list-all` file, so I'm closing this.

**Comment by mikestephens** [comment]
Sorry y'all, this must've gotten lost in the void

**Pull request closed without merging**
